filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/json_access.log
  tags: ["nginx_logs"]
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  fields_under_root: true
  fields:
    logs_type: "nginx_logs"

processors:
 - drop_fields:
    fields: ["ecs","agent","host","cloud","@version"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.redis:
  hosts: ["redis:6379"]
  key: "bole-nginx_logs"
  db: 0
  timeout: 5
  keys:
    - key: "bole-nginx_logs"
      when.contains:
        logs_type: "nginx_logs"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
